const aminoAcidNames = {
  A: "Alanine",
  C: "Cysteine",
  D: "Aspartic acid",
  E: "Glutamic acid",
  F: "Phenylalanine",
  G: "Glycine",
  H: "Histidine",
  I: "Isoleucine",
  K: "Lysine",
  L: "Leucine",
  M: "Methionine",
  N: "Asparagine",
  P: "Proline",
  Q: "Glutamine",
  R: "Arginine",
  S: "Serine",
  T: "Threonine",
  V: "Valine",
  W: "Tryptophan",
  Y: "Tyrosine"
};

const aminoAcidNamesFIN = {
  A: "Alaniini",
  C: "Kysteiini",
  D: "Asparagiinihappo",
  E: "Glutamaattihappo",
  F: "Fenyylialaniini",
  G: "Glysiini",
  H: "Histidiini",
  I: "Isoleusiini",
  K: "Lysiini",
  L: "Leusiini",
  M: "Metioniini",
  N: "Asparagiini",
  P: "Proliini",
  Q: "Glutamiini",
  R: "Arginiini",
  S: "Seriini",
  T: "Treoniini",
  V: "Valiini",
  W: "Tryptofaani",
  Y: "Tyrosiini"
};

