from collections import Counter

def aa_frequencies(seq):
    counts = Counter(seq)
    total = sum(counts.values())
    return {aa: round(count / total * 100, 2) for aa, count in sorted(counts.items())}

sequence = "MGLQRFSFFVTLALVARSLAAIGPVASLVVANAPVSPDGFLRDAIVVNGVVPSPLITGKKGDRFQLNVDDTLTNHSMLKSTSIHWHGFFQAGTNWADGPAFVNQCPIASGHSFLYDFHVPDQAGTFWYHSHLSTQYCDGLRGPFVVYDPKDPHASRYDVDNESTVITLTDWYHTAARLGPRFPLGADATLINGLGRSASTPTAALAVINVQHGKRYRFRLVSISCDPNYTFSIDGHNLTVIEVDGINSQPLLVDSIQIFAAQRYSFVLNANQTVGNYWVRANPNFGTVGFAGGINSAILRYQGAPVAEPTTTQTTSVIPLIETNLHPLARMPVPGSPTPGGVDKALNLAFNFNGTNFFINNATFTPPTVPVLLQILSGAQTAQDLLPAGSVYPLPAHSTIEITLPATALAPGAPHPFHLHGHAFAVVRSAGSTTYNYNDPIFRDVVSTGTPAAGDNVTIRFQTDNPGPWFLHCHIDFHLDAGFAIVFAEDVADVKAANPVPKAWSDLCPIYDGLSEANQ"  # paste full sequence here
freqs = aa_frequencies(sequence)

for aa, freq in freqs.items():
    print(f"{aa}: {freq}%")
