const collieSmooth = [
  {
    "sex": "female",
    "weight_kg": 22.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 1.0
  },
  {
    "sex": "female",
    "weight_kg": 19.0,
    "daily_exercise": "2-3_hours",
    "Calm": 5.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 19.0,
    "daily_exercise": "2-3_hours",
    "Calm": 4.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 3.0
  },
  {
    "sex": "female",
    "weight_kg": 20.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 3.0
  },
  {
    "sex": "female",
    "weight_kg": 23.0,
    "daily_exercise": "1-2_hours",
    "Calm": 3.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 1.0
  },
  {
    "sex": "female",
    "weight_kg": 23.5,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 3.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 23.0,
    "daily_exercise": "2-3_hours",
    "Calm": 4.0,
    "Energetic": 2.0,
    "Active": 2.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": 21.0,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 3.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 5.0,
    "Vocal": 3.0
  },
  {
    "sex": "female",
    "weight_kg": 21.0,
    "daily_exercise": "2-3_hours",
    "Calm": 5.0,
    "Energetic": 3.0,
    "Active": 1.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 24.0,
    "daily_exercise": "under_1_hour",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 3.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 1.0
  },
  {
    "sex": "female",
    "weight_kg": 27.0,
    "daily_exercise": "2-3_hours",
    "Calm": 4.0,
    "Energetic": 2.0,
    "Active": 2.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": 23.0,
    "daily_exercise": "2-3_hours",
    "Calm": 4.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": 17.0,
    "daily_exercise": "1-2_hours",
    "Calm": 3.0,
    "Energetic": 5.0,
    "Active": 3.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 3.0
  },
  {
    "sex": "female",
    "weight_kg": 20.5,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 1.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 4.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 26.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 4.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 23.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 2.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 21.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 5.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 1.0
  },
  {
    "sex": "female",
    "weight_kg": 20.3,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 5.0,
    "Active": 2.0,
    "Human_oriented": 1.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": 20.0,
    "daily_exercise": "2-3_hours",
    "Calm": 1.0,
    "Energetic": 2.0,
    "Active": 4.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 4.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 21.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 2.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": 26.0,
    "daily_exercise": "2-3_hours",
    "Calm": 5.0,
    "Energetic": 4.0,
    "Active": 3.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 1.0
  },
  {
    "sex": "female",
    "weight_kg": NaN,
    "daily_exercise": NaN,
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": 18.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 20.5,
    "daily_exercise": "over_3_hours",
    "Calm": 4.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": NaN,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": NaN,
    "daily_exercise": NaN,
    "Calm": 4.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": NaN,
    "daily_exercise": NaN,
    "Calm": 1.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 4.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 26.0,
    "daily_exercise": "2-3_hours",
    "Calm": 5.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 23.0,
    "daily_exercise": "2-3_hours",
    "Calm": 3.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": 22.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 23.0,
    "daily_exercise": "under_1_hour",
    "Calm": 1.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 4.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 16.0,
    "daily_exercise": "1-2_hours",
    "Calm": 1.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 1.0,
    "Impulsive": 4.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 16.5,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 20.0,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 21.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 21.0,
    "daily_exercise": "2-3_hours",
    "Calm": 1.0,
    "Energetic": 4.0,
    "Active": 3.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 4.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 19.0,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 3.0,
    "Active": 3.0,
    "Human_oriented": 1.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 23.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 1.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 3.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 22.0,
    "daily_exercise": "1-2_hours",
    "Calm": 1.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": 19.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 4.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 25.0,
    "daily_exercise": "over_3_hours",
    "Calm": 1.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 4.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 19.5,
    "daily_exercise": "under_1_hour",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 3.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": 22.7,
    "daily_exercise": "1-2_hours",
    "Calm": 1.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 3.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 17.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 4.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 17.0,
    "daily_exercise": "under_1_hour",
    "Calm": 5.0,
    "Energetic": 3.0,
    "Active": 3.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": 20.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": 20.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 1.0,
    "Active": 2.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 1.0
  },
  {
    "sex": "female",
    "weight_kg": 19.0,
    "daily_exercise": "1-2_hours",
    "Calm": 3.0,
    "Energetic": 5.0,
    "Active": 2.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 19.5,
    "daily_exercise": "2-3_hours",
    "Calm": 4.0,
    "Energetic": 3.0,
    "Active": 1.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": 23.0,
    "daily_exercise": "under_1_hour",
    "Calm": 4.0,
    "Energetic": 1.0,
    "Active": 2.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 1.0
  },
  {
    "sex": "female",
    "weight_kg": 20.85,
    "daily_exercise": "2-3_hours",
    "Calm": 4.0,
    "Energetic": 5.0,
    "Active": 3.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 4.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 19.0,
    "daily_exercise": "2-3_hours",
    "Calm": 4.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 4.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 16.7,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 17.0,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 18.5,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 3.0
  },
  {
    "sex": "female",
    "weight_kg": 18.0,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 3.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 3.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 22.0,
    "daily_exercise": "2-3_hours",
    "Calm": 4.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 26.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 1.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 25.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 3.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 16.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 15.0,
    "daily_exercise": "under_1_hour",
    "Calm": 1.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": NaN,
    "daily_exercise": "over_3_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 21.0,
    "daily_exercise": "over_3_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 21.7,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 1.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 23.0,
    "daily_exercise": "over_3_hours",
    "Calm": 5.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 21.0,
    "daily_exercise": "2-3_hours",
    "Calm": 4.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": 22.0,
    "daily_exercise": "2-3_hours",
    "Calm": 5.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 18.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 20.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 2.0,
    "Active": 2.0,
    "Human_oriented": 1.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 24.0,
    "daily_exercise": "2-3_hours",
    "Calm": 4.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 20.0,
    "daily_exercise": "2-3_hours",
    "Calm": 1.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 4.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 23.0,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 1.0
  },
  {
    "sex": "female",
    "weight_kg": 16.0,
    "daily_exercise": "over_3_hours",
    "Calm": 4.0,
    "Energetic": 2.0,
    "Active": 2.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 23.0,
    "daily_exercise": "1-2_hours",
    "Calm": 3.0,
    "Energetic": 3.0,
    "Active": 2.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 2.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 20.0,
    "daily_exercise": "1-2_hours",
    "Calm": 3.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 2.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": NaN,
    "daily_exercise": NaN,
    "Calm": 4.0,
    "Energetic": 2.0,
    "Active": 2.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 2.0
  },
  {
    "sex": "male",
    "weight_kg": 23.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 2.0,
    "Active": 2.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 1.0
  },
  {
    "sex": "male",
    "weight_kg": 28.0,
    "daily_exercise": "2-3_hours",
    "Calm": 4.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 30.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 5.0,
    "Active": 3.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 4.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 25.5,
    "daily_exercise": "1-2_hours",
    "Calm": 5.0,
    "Energetic": 3.0,
    "Active": 4.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 2.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 22.0,
    "daily_exercise": "under_1_hour",
    "Calm": 4.0,
    "Energetic": 5.0,
    "Active": 2.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 2.0
  },
  {
    "sex": "male",
    "weight_kg": 30.0,
    "daily_exercise": "under_1_hour",
    "Calm": 5.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 31.0,
    "daily_exercise": "2-3_hours",
    "Calm": 3.0,
    "Energetic": 4.0,
    "Active": 3.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 30.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 1.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 20.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 5.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 20.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 2.0,
    "Active": 2.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 2.0,
    "Vocal": 2.0
  },
  {
    "sex": "male",
    "weight_kg": 26.0,
    "daily_exercise": "1-2_hours",
    "Calm": 5.0,
    "Energetic": 1.0,
    "Active": 1.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 2.0,
    "Impulsive": 1.0,
    "Vocal": 1.0
  },
  {
    "sex": "male",
    "weight_kg": 30.0,
    "daily_exercise": "1-2_hours",
    "Calm": 5.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 26.0,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 28.0,
    "daily_exercise": "over_3_hours",
    "Calm": 5.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "male",
    "weight_kg": 25.0,
    "daily_exercise": "2-3_hours",
    "Calm": 4.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 3.0
  },
  {
    "sex": "male",
    "weight_kg": NaN,
    "daily_exercise": "1-2_hours",
    "Calm": 5.0,
    "Energetic": 2.0,
    "Active": 2.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": NaN,
    "daily_exercise": "1-2_hours",
    "Calm": 1.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 25.0,
    "daily_exercise": "1-2_hours",
    "Calm": 5.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 1.0
  },
  {
    "sex": "male",
    "weight_kg": 26.0,
    "daily_exercise": "under_1_hour",
    "Calm": 1.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 1.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 24.5,
    "daily_exercise": "2-3_hours",
    "Calm": 1.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 1.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 5.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 26.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 2.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 29.0,
    "daily_exercise": NaN,
    "Calm": 1.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 29.0,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 31.0,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 4.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": NaN,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 3.0,
    "Active": 2.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 3.0,
    "Impulsive": 2.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 21.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 29.0,
    "daily_exercise": "2-3_hours",
    "Calm": 1.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 4.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 27.0,
    "daily_exercise": "2-3_hours",
    "Calm": 5.0,
    "Energetic": 3.0,
    "Active": 2.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "male",
    "weight_kg": 28.0,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 3.0,
    "Vocal": 3.0
  },
  {
    "sex": "male",
    "weight_kg": 27.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 4.0,
    "Active": 3.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "male",
    "weight_kg": NaN,
    "daily_exercise": NaN,
    "Calm": 1.0,
    "Energetic": 1.0,
    "Active": 2.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 2.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 25.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 2.0,
    "Active": 2.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 2.0
  },
  {
    "sex": "male",
    "weight_kg": 31.0,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 2.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": NaN,
    "daily_exercise": NaN,
    "Calm": 4.0,
    "Energetic": 2.0,
    "Active": 2.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 3.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "male",
    "weight_kg": 23.0,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 2.0,
    "Impulsive": 4.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 25.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 24.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 5.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 29.0,
    "daily_exercise": "1-2_hours",
    "Calm": 5.0,
    "Energetic": 2.0,
    "Active": 2.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "male",
    "weight_kg": 23.0,
    "daily_exercise": "2-3_hours",
    "Calm": 5.0,
    "Energetic": 2.0,
    "Active": 1.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 5.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 24.0,
    "daily_exercise": "1-2_hours",
    "Calm": 5.0,
    "Energetic": 4.0,
    "Active": 5.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 25.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 2.0,
    "Vocal": 2.0
  },
  {
    "sex": "male",
    "weight_kg": 32.0,
    "daily_exercise": "2-3_hours",
    "Calm": 4.0,
    "Energetic": 3.0,
    "Active": 4.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 33.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 1.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 5.0,
    "Vocal": 3.0
  },
  {
    "sex": "male",
    "weight_kg": NaN,
    "daily_exercise": NaN,
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 3.0,
    "Impulsive": 4.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 23.0,
    "daily_exercise": "under_1_hour",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "male",
    "weight_kg": 29.0,
    "daily_exercise": "under_1_hour",
    "Calm": 4.0,
    "Energetic": 3.0,
    "Active": 2.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 28.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 2.0
  },
  {
    "sex": "male",
    "weight_kg": 23.7,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 26.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 25.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 29.7,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 4.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 24.0,
    "daily_exercise": "2-3_hours",
    "Calm": 1.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 32.0,
    "daily_exercise": "over_3_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 26.0,
    "daily_exercise": "1-2_hours",
    "Calm": 5.0,
    "Energetic": 5.0,
    "Active": 3.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "male",
    "weight_kg": NaN,
    "daily_exercise": "2-3_hours",
    "Calm": 1.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 2.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 24.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 1.0,
    "Willing_to_learn": 2.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 32.0,
    "daily_exercise": "over_3_hours",
    "Calm": 4.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 28.0,
    "daily_exercise": "1-2_hours",
    "Calm": 1.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 4.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 26.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 5.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 23.2,
    "daily_exercise": NaN,
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 3.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 23.7,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 3.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 26.0,
    "daily_exercise": "over_3_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 3.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 28.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 4.0,
    "Active": 1.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 31.0,
    "daily_exercise": "1-2_hours",
    "Calm": 1.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 4.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 28.0,
    "daily_exercise": "2-3_hours",
    "Calm": 1.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 4.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 29.0,
    "daily_exercise": "2-3_hours",
    "Calm": 5.0,
    "Energetic": 2.0,
    "Active": 2.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 1.0
  },
  {
    "sex": "male",
    "weight_kg": NaN,
    "daily_exercise": NaN,
    "Calm": 1.0,
    "Energetic": 4.0,
    "Active": 3.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 3.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 25.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 2.0,
    "Active": 3.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 27.0,
    "daily_exercise": "2-3_hours",
    "Calm": 5.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 30.0,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 1.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 4.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 25.0,
    "daily_exercise": "1-2_hours",
    "Calm": 1.0,
    "Energetic": 4.0,
    "Active": 3.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  }
];
const collieRough = [
  {
    "sex": "female",
    "weight_kg": 22.0,
    "daily_exercise": "2-3_hours",
    "Calm": 4.0,
    "Energetic": 2.0,
    "Active": 2.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 4.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": 16.0,
    "daily_exercise": "2-3_hours",
    "Calm": 1.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 2.0,
    "Impulsive": 3.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 22.0,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": 27.0,
    "daily_exercise": "2-3_hours",
    "Calm": 1.0,
    "Energetic": 4.0,
    "Active": 3.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": NaN,
    "daily_exercise": "2-3_hours",
    "Calm": 1.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 4.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 26.0,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 25.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 19.0,
    "daily_exercise": "2-3_hours",
    "Calm": 3.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 3.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 22.0,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 1.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 21.0,
    "daily_exercise": "2-3_hours",
    "Calm": 5.0,
    "Energetic": 2.0,
    "Active": 2.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 21.0,
    "daily_exercise": "under_1_hour",
    "Calm": 4.0,
    "Energetic": 3.0,
    "Active": 3.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 26.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 20.0,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 24.0,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 4.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": NaN,
    "daily_exercise": "2-3_hours",
    "Calm": 5.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": 17.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 4.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 18.0,
    "daily_exercise": "1-2_hours",
    "Calm": 3.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": 19.89,
    "daily_exercise": "1-2_hours",
    "Calm": 5.0,
    "Energetic": 2.0,
    "Active": 2.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": 20.0,
    "daily_exercise": "2-3_hours",
    "Calm": 3.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 4.0,
    "Vocal": 1.0
  },
  {
    "sex": "female",
    "weight_kg": 27.0,
    "daily_exercise": "2-3_hours",
    "Calm": 5.0,
    "Energetic": 2.0,
    "Active": 2.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 3.0,
    "Impulsive": 1.0,
    "Vocal": 1.0
  },
  {
    "sex": "female",
    "weight_kg": 19.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 20.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 3.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 20.0,
    "daily_exercise": "under_1_hour",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 5.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 18.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 5.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 3.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 16.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 3.0,
    "Active": 1.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": 22.0,
    "daily_exercise": "under_1_hour",
    "Calm": 4.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 4.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 22.0,
    "daily_exercise": "under_1_hour",
    "Calm": 4.0,
    "Energetic": 5.0,
    "Active": 1.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 3.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 18.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 2.0,
    "Active": 5.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": NaN,
    "daily_exercise": "under_1_hour",
    "Calm": 5.0,
    "Energetic": 2.0,
    "Active": 2.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 1.0
  },
  {
    "sex": "female",
    "weight_kg": 22.0,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 4.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": NaN,
    "daily_exercise": "under_1_hour",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": NaN,
    "daily_exercise": "under_1_hour",
    "Calm": 1.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 4.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": NaN,
    "daily_exercise": "under_1_hour",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": NaN,
    "daily_exercise": "under_1_hour",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 21.0,
    "daily_exercise": "1-2_hours",
    "Calm": 5.0,
    "Energetic": 2.0,
    "Active": 4.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": 18.0,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 4.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 19.0,
    "daily_exercise": NaN,
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 5.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 3.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 22.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 18.0,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 3.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 17.0,
    "daily_exercise": "1-2_hours",
    "Calm": 5.0,
    "Energetic": 3.0,
    "Active": 2.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": 17.0,
    "daily_exercise": "1-2_hours",
    "Calm": 3.0,
    "Energetic": 3.0,
    "Active": 2.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 22.5,
    "daily_exercise": NaN,
    "Calm": 4.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": NaN,
    "daily_exercise": NaN,
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 2.0,
    "Impulsive": 2.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 17.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 2.0,
    "Active": 2.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 20.0,
    "daily_exercise": "2-3_hours",
    "Calm": 5.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 1.0
  },
  {
    "sex": "female",
    "weight_kg": 18.0,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 4.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 20.0,
    "daily_exercise": "over_3_hours",
    "Calm": 5.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 1.0
  },
  {
    "sex": "female",
    "weight_kg": 22.0,
    "daily_exercise": "2-3_hours",
    "Calm": 4.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 25.0,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 17.7,
    "daily_exercise": NaN,
    "Calm": 5.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 1.0
  },
  {
    "sex": "female",
    "weight_kg": 18.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 3.0,
    "Active": 3.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 21.0,
    "daily_exercise": "2-3_hours",
    "Calm": 5.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": NaN,
    "daily_exercise": NaN,
    "Calm": 3.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 23.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 2.0,
    "Active": 2.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": 25.0,
    "daily_exercise": "2-3_hours",
    "Calm": 5.0,
    "Energetic": 3.0,
    "Active": 3.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 20.4,
    "daily_exercise": "1-2_hours",
    "Calm": 5.0,
    "Energetic": 2.0,
    "Active": 2.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": 16.0,
    "daily_exercise": "1-2_hours",
    "Calm": 1.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 4.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 23.0,
    "daily_exercise": "over_3_hours",
    "Calm": 5.0,
    "Energetic": 1.0,
    "Active": 1.0,
    "Human_oriented": 1.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 1.0
  },
  {
    "sex": "female",
    "weight_kg": 18.8,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 2.0,
    "Active": 3.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 2.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 22.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 3.0,
    "Active": 2.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 3.0
  },
  {
    "sex": "female",
    "weight_kg": NaN,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 3.0,
    "Active": 4.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": NaN,
    "daily_exercise": NaN,
    "Calm": 4.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": NaN,
    "daily_exercise": NaN,
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 4.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": NaN,
    "daily_exercise": NaN,
    "Calm": 5.0,
    "Energetic": 4.0,
    "Active": 1.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 1.0
  },
  {
    "sex": "female",
    "weight_kg": 15.8,
    "daily_exercise": "2-3_hours",
    "Calm": 5.0,
    "Energetic": 5.0,
    "Active": 2.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 1.0
  },
  {
    "sex": "female",
    "weight_kg": NaN,
    "daily_exercise": "1-2_hours",
    "Calm": 5.0,
    "Energetic": 3.0,
    "Active": 2.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 18.0,
    "daily_exercise": "2-3_hours",
    "Calm": 3.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 19.0,
    "daily_exercise": "2-3_hours",
    "Calm": 4.0,
    "Energetic": 1.0,
    "Active": 2.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": 17.5,
    "daily_exercise": "under_1_hour",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": 20.5,
    "daily_exercise": "1-2_hours",
    "Calm": 3.0,
    "Energetic": 3.0,
    "Active": 2.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 20.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 18.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 4.0,
    "Active": 3.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 23.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 4.0,
    "Active": 3.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 20.0,
    "daily_exercise": "2-3_hours",
    "Calm": 5.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 1.0
  },
  {
    "sex": "female",
    "weight_kg": 17.0,
    "daily_exercise": "under_1_hour",
    "Calm": 2.0,
    "Energetic": 2.0,
    "Active": 2.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 21.0,
    "daily_exercise": "over_3_hours",
    "Calm": 5.0,
    "Energetic": 3.0,
    "Active": 3.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": 18.0,
    "daily_exercise": "over_3_hours",
    "Calm": 1.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 2.0,
    "Impulsive": 4.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 19.0,
    "daily_exercise": "over_3_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": NaN,
    "daily_exercise": "1-2_hours",
    "Calm": 5.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 1.0
  },
  {
    "sex": "female",
    "weight_kg": 20.0,
    "daily_exercise": "over_3_hours",
    "Calm": 4.0,
    "Energetic": 4.0,
    "Active": 3.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 22.0,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": 24.0,
    "daily_exercise": "2-3_hours",
    "Calm": 3.0,
    "Energetic": 4.0,
    "Active": 3.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 4.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": 21.0,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 24.6,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": NaN,
    "daily_exercise": NaN,
    "Calm": 3.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 5.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 20.0,
    "daily_exercise": "under_1_hour",
    "Calm": 4.0,
    "Energetic": 2.0,
    "Active": 1.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 17.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 2.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 4.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 18.4,
    "daily_exercise": "2-3_hours",
    "Calm": 5.0,
    "Energetic": 3.0,
    "Active": 1.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": NaN,
    "daily_exercise": NaN,
    "Calm": 1.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": NaN,
    "daily_exercise": NaN,
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 1.0,
    "Impulsive": 2.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": 26.0,
    "daily_exercise": NaN,
    "Calm": 5.0,
    "Energetic": 1.0,
    "Active": 1.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 21.0,
    "daily_exercise": "1-2_hours",
    "Calm": 3.0,
    "Energetic": 5.0,
    "Active": 2.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 19.0,
    "daily_exercise": "2-3_hours",
    "Calm": 3.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 1.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 1.0
  },
  {
    "sex": "female",
    "weight_kg": 20.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 1.0
  },
  {
    "sex": "female",
    "weight_kg": 20.0,
    "daily_exercise": "over_3_hours",
    "Calm": 1.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 1.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 3.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 22.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": 19.0,
    "daily_exercise": "over_3_hours",
    "Calm": 4.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": 23.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": 16.9,
    "daily_exercise": "2-3_hours",
    "Calm": 3.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 3.0,
    "Vocal": 2.0
  },
  {
    "sex": "female",
    "weight_kg": 18.0,
    "daily_exercise": "2-3_hours",
    "Calm": 3.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 1.0
  },
  {
    "sex": "female",
    "weight_kg": 30.0,
    "daily_exercise": "1-2_hours",
    "Calm": 3.0,
    "Energetic": 4.0,
    "Active": 3.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 3.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": 22.0,
    "daily_exercise": "over_3_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": NaN,
    "daily_exercise": NaN,
    "Calm": 1.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 4.0,
    "Vocal": 5.0
  },
  {
    "sex": "female",
    "weight_kg": NaN,
    "daily_exercise": "2-3_hours",
    "Calm": 4.0,
    "Energetic": 5.0,
    "Active": 3.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "female",
    "weight_kg": NaN,
    "daily_exercise": "2-3_hours",
    "Calm": 5.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 1.0
  },
  {
    "sex": "male",
    "weight_kg": 18.0,
    "daily_exercise": "1-2_hours",
    "Calm": 5.0,
    "Energetic": 2.0,
    "Active": 2.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "male",
    "weight_kg": 28.0,
    "daily_exercise": "over_3_hours",
    "Calm": 5.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 1.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 23.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 3.0,
    "Active": 2.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "male",
    "weight_kg": 19.2,
    "daily_exercise": "2-3_hours",
    "Calm": 4.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 3.0
  },
  {
    "sex": "male",
    "weight_kg": 23.0,
    "daily_exercise": "1-2_hours",
    "Calm": 1.0,
    "Energetic": 4.0,
    "Active": 3.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 2.0,
    "Vocal": 3.0
  },
  {
    "sex": "male",
    "weight_kg": 21.8,
    "daily_exercise": "2-3_hours",
    "Calm": 1.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 1.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 4.0,
    "Vocal": 3.0
  },
  {
    "sex": "male",
    "weight_kg": 18.0,
    "daily_exercise": NaN,
    "Calm": 4.0,
    "Energetic": 2.0,
    "Active": 2.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 20.9,
    "daily_exercise": "over_3_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 2.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 3.0,
    "Impulsive": 4.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 29.0,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 3.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 30.0,
    "daily_exercise": "2-3_hours",
    "Calm": 4.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 28.0,
    "daily_exercise": "2-3_hours",
    "Calm": 3.0,
    "Energetic": 4.0,
    "Active": 3.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 24.0,
    "daily_exercise": "1-2_hours",
    "Calm": 3.0,
    "Energetic": 5.0,
    "Active": 3.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 35.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 4.0,
    "Active": 3.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "male",
    "weight_kg": 22.0,
    "daily_exercise": "2-3_hours",
    "Calm": 5.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 24.0,
    "daily_exercise": "under_1_hour",
    "Calm": 4.0,
    "Energetic": 2.0,
    "Active": 2.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 2.0,
    "Impulsive": 2.0,
    "Vocal": 2.0
  },
  {
    "sex": "male",
    "weight_kg": 24.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 28.0,
    "daily_exercise": "2-3_hours",
    "Calm": 4.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": NaN,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": NaN,
    "daily_exercise": "over_3_hours",
    "Calm": 5.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 27.0,
    "daily_exercise": "2-3_hours",
    "Calm": 3.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 4.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": NaN,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 3.0,
    "Active": 4.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "male",
    "weight_kg": NaN,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 4.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 18.0,
    "daily_exercise": "over_3_hours",
    "Calm": 5.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 1.0
  },
  {
    "sex": "male",
    "weight_kg": 20.0,
    "daily_exercise": "2-3_hours",
    "Calm": 3.0,
    "Energetic": 3.0,
    "Active": 4.0,
    "Human_oriented": 1.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 3.0
  },
  {
    "sex": "male",
    "weight_kg": 24.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 2.0,
    "Active": 1.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": NaN,
    "daily_exercise": "under_1_hour",
    "Calm": 4.0,
    "Energetic": 2.0,
    "Active": 4.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "male",
    "weight_kg": 26.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 27.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 3.0,
    "Active": 2.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 2.0,
    "Vocal": 3.0
  },
  {
    "sex": "male",
    "weight_kg": 24.0,
    "daily_exercise": "2-3_hours",
    "Calm": 4.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 21.0,
    "daily_exercise": "1-2_hours",
    "Calm": 1.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 4.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 20.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 2.0,
    "Vocal": 2.0
  },
  {
    "sex": "male",
    "weight_kg": 30.0,
    "daily_exercise": "2-3_hours",
    "Calm": 4.0,
    "Energetic": 4.0,
    "Active": 3.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 3.0
  },
  {
    "sex": "male",
    "weight_kg": 24.0,
    "daily_exercise": "2-3_hours",
    "Calm": 1.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 25.0,
    "daily_exercise": "2-3_hours",
    "Calm": 5.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 20.4,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "male",
    "weight_kg": 29.0,
    "daily_exercise": "2-3_hours",
    "Calm": 1.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 4.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 24.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 3.0,
    "Active": 2.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 1.0
  },
  {
    "sex": "male",
    "weight_kg": NaN,
    "daily_exercise": "2-3_hours",
    "Calm": 1.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 4.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 22.0,
    "daily_exercise": "1-2_hours",
    "Calm": 3.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 5.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": NaN,
    "daily_exercise": NaN,
    "Calm": 4.0,
    "Energetic": 3.0,
    "Active": 4.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 3.0,
    "Impulsive": 4.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 25.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 25.0,
    "daily_exercise": "over_3_hours",
    "Calm": 4.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 20.0,
    "daily_exercise": "2-3_hours",
    "Calm": 3.0,
    "Energetic": 3.0,
    "Active": 3.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 3.0
  },
  {
    "sex": "male",
    "weight_kg": 26.9,
    "daily_exercise": "2-3_hours",
    "Calm": 5.0,
    "Energetic": 4.0,
    "Active": 3.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 27.0,
    "daily_exercise": "2-3_hours",
    "Calm": 5.0,
    "Energetic": 2.0,
    "Active": 2.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "male",
    "weight_kg": NaN,
    "daily_exercise": "under_1_hour",
    "Calm": 5.0,
    "Energetic": 2.0,
    "Active": 1.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 1.0
  },
  {
    "sex": "male",
    "weight_kg": NaN,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 22.0,
    "daily_exercise": "2-3_hours",
    "Calm": 4.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 25.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 3.0,
    "Human_oriented": 1.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 31.0,
    "daily_exercise": "1-2_hours",
    "Calm": 5.0,
    "Energetic": 3.0,
    "Active": 4.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 23.5,
    "daily_exercise": "over_3_hours",
    "Calm": 5.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 25.0,
    "daily_exercise": "1-2_hours",
    "Calm": 1.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 2.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 32.0,
    "daily_exercise": NaN,
    "Calm": 4.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "male",
    "weight_kg": 34.0,
    "daily_exercise": "2-3_hours",
    "Calm": 4.0,
    "Energetic": 5.0,
    "Active": 3.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 24.0,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "male",
    "weight_kg": 22.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 2.0,
    "Active": 2.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 27.0,
    "daily_exercise": "under_1_hour",
    "Calm": 5.0,
    "Energetic": 3.0,
    "Active": 4.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "male",
    "weight_kg": 25.0,
    "daily_exercise": "1-2_hours",
    "Calm": 5.0,
    "Energetic": 2.0,
    "Active": 2.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 25.0,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 3.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 4.0,
    "Vocal": 2.0
  },
  {
    "sex": "male",
    "weight_kg": NaN,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 3.0,
    "Impulsive": 3.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 32.0,
    "daily_exercise": "1-2_hours",
    "Calm": 3.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 5.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 24.6,
    "daily_exercise": "2-3_hours",
    "Calm": 4.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 19.2,
    "daily_exercise": "2-3_hours",
    "Calm": 4.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 21.0,
    "daily_exercise": NaN,
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 3.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 23.0,
    "daily_exercise": "2-3_hours",
    "Calm": 4.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 2.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 20.0,
    "daily_exercise": "over_3_hours",
    "Calm": 5.0,
    "Energetic": 2.0,
    "Active": 2.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 1.0
  },
  {
    "sex": "male",
    "weight_kg": 24.0,
    "daily_exercise": "1-2_hours",
    "Calm": 4.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 28.0,
    "daily_exercise": "over_3_hours",
    "Calm": 3.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 2.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": NaN,
    "daily_exercise": NaN,
    "Calm": 5.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 27.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 2.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 4.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 22.0,
    "daily_exercise": "1-2_hours",
    "Calm": 5.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 1.0
  },
  {
    "sex": "male",
    "weight_kg": 21.0,
    "daily_exercise": "2-3_hours",
    "Calm": 4.0,
    "Energetic": 2.0,
    "Active": 2.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 25.0,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": NaN,
    "daily_exercise": NaN,
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 3.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 28.0,
    "daily_exercise": "1-2_hours",
    "Calm": 5.0,
    "Energetic": 2.0,
    "Active": 2.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 20.0,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 24.0,
    "daily_exercise": "over_3_hours",
    "Calm": 3.0,
    "Energetic": 2.0,
    "Active": 2.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 2.0
  },
  {
    "sex": "male",
    "weight_kg": 18.0,
    "daily_exercise": "2-3_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 3.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 26.0,
    "daily_exercise": "over_3_hours",
    "Calm": 5.0,
    "Energetic": 3.0,
    "Active": 2.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "male",
    "weight_kg": 30.0,
    "daily_exercise": "2-3_hours",
    "Calm": 4.0,
    "Energetic": 3.0,
    "Active": 3.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 2.0,
    "Vocal": 2.0
  },
  {
    "sex": "male",
    "weight_kg": 28.0,
    "daily_exercise": "under_1_hour",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 2.0
  },
  {
    "sex": "male",
    "weight_kg": 29.0,
    "daily_exercise": "under_1_hour",
    "Calm": 4.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 4.0,
    "Vocal": 2.0
  },
  {
    "sex": "male",
    "weight_kg": NaN,
    "daily_exercise": NaN,
    "Calm": 4.0,
    "Energetic": 2.0,
    "Active": 2.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 17.0,
    "daily_exercise": "over_3_hours",
    "Calm": 1.0,
    "Energetic": 5.0,
    "Active": 4.0,
    "Human_oriented": 3.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 23.0,
    "daily_exercise": "1-2_hours",
    "Calm": 5.0,
    "Energetic": 2.0,
    "Active": 1.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 2.0,
    "Impulsive": 1.0,
    "Vocal": 1.0
  },
  {
    "sex": "male",
    "weight_kg": 31.1,
    "daily_exercise": "1-2_hours",
    "Calm": 5.0,
    "Energetic": 2.0,
    "Active": 2.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": 21.5,
    "daily_exercise": "1-2_hours",
    "Calm": 2.0,
    "Energetic": 5.0,
    "Active": 5.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 4.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 20.3,
    "daily_exercise": "over_3_hours",
    "Calm": 5.0,
    "Energetic": 4.0,
    "Active": 3.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 24.5,
    "daily_exercise": "2-3_hours",
    "Calm": 4.0,
    "Energetic": 4.0,
    "Active": 1.0,
    "Human_oriented": 5.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 30.0,
    "daily_exercise": "2-3_hours",
    "Calm": 5.0,
    "Energetic": 1.0,
    "Active": 1.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 4.0,
    "Impulsive": 1.0,
    "Vocal": 1.0
  },
  {
    "sex": "male",
    "weight_kg": 29.0,
    "daily_exercise": "over_3_hours",
    "Calm": 4.0,
    "Energetic": 5.0,
    "Active": 2.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 5.0
  },
  {
    "sex": "male",
    "weight_kg": 29.0,
    "daily_exercise": "over_3_hours",
    "Calm": 5.0,
    "Energetic": 5.0,
    "Active": 1.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 2.0
  },
  {
    "sex": "male",
    "weight_kg": 21.9,
    "daily_exercise": NaN,
    "Calm": 2.0,
    "Energetic": 4.0,
    "Active": 4.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 2.0,
    "Vocal": 4.0
  },
  {
    "sex": "male",
    "weight_kg": NaN,
    "daily_exercise": "1-2_hours",
    "Calm": 3.0,
    "Energetic": 5.0,
    "Active": 3.0,
    "Human_oriented": 4.0,
    "Willing_to_learn": 2.0,
    "Impulsive": 2.0,
    "Vocal": 2.0
  },
  {
    "sex": "male",
    "weight_kg": 22.0,
    "daily_exercise": "2-3_hours",
    "Calm": 5.0,
    "Energetic": 4.0,
    "Active": 2.0,
    "Human_oriented": 2.0,
    "Willing_to_learn": 5.0,
    "Impulsive": 1.0,
    "Vocal": 4.0
  }
];
